name: 'Repo Lockdown'

on:
  pull_request_target:
    types: opened

permissions:
  issues: write
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v4
        with:
          pr-comment: 'Hi! Thank you for your contribution.

          This repo is only a mirror and unfortunately we can''t accept PRs made here. Please re-submit your changes to [our Gitea instance](https://kolaente.dev/vikunja/vikunja/pulls).

          Also check out the [contribution guidelines](https://vikunja.io/docs/development/#pull-requests).

          Thank you for your understanding.'
